title: ImageXD
description: Image processing across domains
sitename: ImageXD
#url: 		'http://bids.github.io/imagexd/'
#baseurl: 'http://bids.github.io/imagexd/'
url: 		'http://localhost:4000'
#baseurl: 'http://bids.github.io/imagexd/'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
